version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8888:8080"
    restart: always
    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.1.23:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=192.168.1.23:2181