apiVersion: v1
kind: Service
metadata:
  name: auth-service-nodeport
spec:
  type: NodePort
  selector:
    app: auth-server
  ports:
  - nodePort: 30009
    port: 8081
    protocol: TCP
    targetPort: 8081
