apiVersion: v1
kind: Service
metadata:
  name: service-service-nodeport
spec:
  type: NodePort
  selector:
    app: service-server
  ports:
  - nodePort: 30011
    port: 8083
    protocol: TCP
    targetPort: 8083
